# Generated by Django 3.1.1 on 2020-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='deck',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
